files:
  - source: /app/src/main/res/values/strings.xml
    translation: /app/src/main/res/values-%two_letters_code%/%original_file_name%
    languages_mapping:
      two_letters_code:
        id: in
    translate_attributes: 0
    update_option: update_as_unapproved
  - source: fastlane/metadata/android/en-US/*.txt
    translation: fastlane/metadata/android/%two_letters_code%/%original_file_name%
